import sys
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QLabel
from text_solver import solve, valid, print_board
from board import Grid, Cube, make_board
import data
import random


def find_label_pos(widget):
    """
    Find the x, y coordinates of label
    :param widget: label
    :return: row, col of label in 2D array
    """
    num = int(widget.objectName())
    if num % 9 == 0 and num != 0:
        if num <= 9:
            row = 0
        else:
            row = num // 9 - 1
        col = num - 9*row - 1
    else:
        row = num // 9
        col = num - 9 * row - 1
    return row, col


# noinspection PyUnresolvedReferences,PyUnresolvedReferences
class ClickableLabel(QLabel):
    """
    Extended QLabel class to enable on-click functionality
    """
    clicked = pyqtSignal()

    def __init__(self, parent=None):
        QLabel.__init__(self, parent)

    def mousePressEvent(self, ev):
        """
        Select square on mouseclick
        :param ev: event
        """
        self.clicked.emit()
        print(self.objectName())
        print(self.parentWidget().objectName())
        x, y = find_label_pos(self)
        if data.gridobj.selected is None:
            data.gridobj.select(x, y)
            self.setStyleSheet("border: 2px solid red")
        else:
            widget = data.labels[data.gridobj.selected[0]][data.gridobj.selected[1]]
            if data.gridobj.cubes[data.gridobj.selected[0]][data.gridobj.selected[1]].value != 0:
                widget.setStyleSheet("border: 2px solid white; color: rgb(40, 255, 6)")
            elif data.gridobj.cubes[data.gridobj.selected[0]][data.gridobj.selected[1]].temp != 0:
                widget.setStyleSheet("border: 2px solid white; color: rgb(243, 219, 9) ")
            else:
                widget.setStyleSheet("border: 2px solid white; color: white ")
            data.gridobj.select(x, y)
            if data.gridobj.cubes[x][y].temp != 0:
                self.setStyleSheet("border: 2px solid red; color: rgb(243, 219, 9)")
            else:
                self.setStyleSheet("border: 2px solid red; color: white")


# noinspection PyAttributeOutsideInit
class UiForm(object):
    """
    Class for main game window
    """
    def setup_ui(self, form):
        """
        Initialize UI elements
        :param form: main window
        """
        form.keyPressEvent = self.keypress
        form.setObjectName("Form")
        form.resize(500, 405)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(form.sizePolicy().hasHeightForWidth())
        form.setSizePolicy(size_policy)
        # noinspection PyArgumentList
        self.line = QtWidgets.QFrame(form)
        self.line.setGeometry(QtCore.QRect(144, 10, 50, 361))
        self.line.setStyleSheet("color: white")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        # noinspection PyArgumentList
        self.line_2 = QtWidgets.QFrame(form)
        self.line_2.setGeometry(QtCore.QRect(317, 10, 30, 361))
        self.line_2.setStyleSheet("color: white")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        # noinspection PyArgumentList
        self.line_3 = QtWidgets.QFrame(form)
        self.line_3.setGeometry(QtCore.QRect(10, 247, 491, 10))
        self.line_3.setStyleSheet("color:white")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        # noinspection PyArgumentList
        self.line_4 = QtWidgets.QFrame(form)
        self.line_4.setGeometry(QtCore.QRect(10, 118, 491, 20))
        self.line_4.setStyleSheet("color:white")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.label = ClickableLabel(form)
        self.label.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.label.setStyleSheet("border: 2px solid white")
        self.label.setText("")
        self.label.setObjectName("1")
        self.label2 = ClickableLabel(form)
        self.label2.setGeometry(QtCore.QRect(70, 30, 31, 21))
        self.label2.setStyleSheet("border: 2px solid white")
        self.label2.setText("")
        self.label2.setObjectName("2")
        self.label3 = ClickableLabel(form)
        self.label3.setGeometry(QtCore.QRect(120, 30, 31, 21))
        self.label3.setStyleSheet("border: 2px solid white")
        self.label3.setText("")
        self.label3.setObjectName("3")
        self.label4 = ClickableLabel(form)
        self.label4.setGeometry(QtCore.QRect(185, 30, 31, 21))
        self.label4.setStyleSheet("border: 2px solid white")
        self.label4.setText("")
        self.label4.setObjectName("4")
        self.label5 = ClickableLabel(form)
        self.label5.setGeometry(QtCore.QRect(235, 30, 31, 21))
        self.label5.setStyleSheet("border: 2px solid white")
        self.label5.setText("")
        self.label5.setObjectName("5")
        self.label6 = ClickableLabel(form)
        self.label6.setGeometry(QtCore.QRect(285, 30, 31, 21))
        self.label6.setStyleSheet("border: 2px solid white")
        self.label6.setText("")
        self.label6.setObjectName("6")
        self.label7 = ClickableLabel(form)
        self.label7.setGeometry(QtCore.QRect(350, 30, 31, 21))
        self.label7.setStyleSheet("border: 2px solid white")
        self.label7.setText("")
        self.label7.setObjectName("7")
        self.label8 = ClickableLabel(form)
        self.label8.setGeometry(QtCore.QRect(400, 30, 31, 21))
        self.label8.setStyleSheet("border: 2px solid white")
        self.label8.setText("")
        self.label8.setObjectName("8")
        self.label9 = ClickableLabel(form)
        self.label9.setGeometry(QtCore.QRect(450, 30, 31, 21))
        self.label9.setStyleSheet("border: 2px solid white")
        self.label9.setText("")
        self.label9.setObjectName("9")
        self.label10 = ClickableLabel(form)
        self.label10.setGeometry(QtCore.QRect(20, 60, 31, 21))
        self.label10.setStyleSheet("border: 2px solid white")
        self.label10.setText("")
        self.label10.setObjectName("10")
        self.label11 = ClickableLabel(form)
        self.label11.setGeometry(QtCore.QRect(70, 60, 31, 21))
        self.label11.setStyleSheet("border: 2px solid white")
        self.label11.setText("")
        self.label11.setObjectName("11")
        self.label12 = ClickableLabel(form)
        self.label12.setGeometry(QtCore.QRect(120, 60, 31, 21))
        self.label12.setStyleSheet("border: 2px solid white")
        self.label12.setText("")
        self.label12.setObjectName("12")
        self.label13 = ClickableLabel(form)
        self.label13.setGeometry(QtCore.QRect(185, 60, 31, 21))
        self.label13.setStyleSheet("border: 2px solid white")
        self.label13.setText("")
        self.label13.setObjectName("13")
        self.label14 = ClickableLabel(form)
        self.label14.setGeometry(QtCore.QRect(235, 60, 31, 21))
        self.label14.setStyleSheet("border: 2px solid white")
        self.label14.setText("")
        self.label14.setObjectName("14")
        self.label15 = ClickableLabel(form)
        self.label15.setGeometry(QtCore.QRect(285, 60, 31, 21))
        self.label15.setStyleSheet("border: 2px solid white")
        self.label15.setText("")
        self.label15.setObjectName("15")
        self.label16 = ClickableLabel(form)
        self.label16.setGeometry(QtCore.QRect(350, 60, 31, 21))
        self.label16.setStyleSheet("border: 2px solid white")
        self.label16.setText("")
        self.label16.setObjectName("16")
        self.label17 = ClickableLabel(form)
        self.label17.setGeometry(QtCore.QRect(400, 60, 31, 21))
        self.label17.setStyleSheet("border: 2px solid white")
        self.label17.setText("")
        self.label17.setObjectName("17")
        self.label18 = ClickableLabel(form)
        self.label18.setGeometry(QtCore.QRect(450, 60, 31, 21))
        self.label18.setStyleSheet("border: 2px solid white")
        self.label18.setText("")
        self.label18.setObjectName("18")
        self.label19 = ClickableLabel(form)
        self.label19.setGeometry(QtCore.QRect(20, 90, 31, 21))
        self.label19.setStyleSheet("border: 2px solid white")
        self.label19.setText("")
        self.label19.setObjectName("19")
        self.label20 = ClickableLabel(form)
        self.label20.setGeometry(QtCore.QRect(70, 90, 31, 21))
        self.label20.setStyleSheet("border: 2px solid white")
        self.label20.setText("")
        self.label20.setObjectName("20")
        self.label21 = ClickableLabel(form)
        self.label21.setGeometry(QtCore.QRect(120, 90, 31, 21))
        self.label21.setStyleSheet("border: 2px solid white")
        self.label21.setText("")
        self.label21.setObjectName("21")
        self.label22 = ClickableLabel(form)
        self.label22.setGeometry(QtCore.QRect(185, 90, 31, 21))
        self.label22.setStyleSheet("border: 2px solid white")
        self.label22.setText("")
        self.label22.setObjectName("22")
        self.label23 = ClickableLabel(form)
        self.label23.setGeometry(QtCore.QRect(235, 90, 31, 21))
        self.label23.setStyleSheet("border: 2px solid white")
        self.label23.setText("")
        self.label23.setObjectName("23")
        self.label24 = ClickableLabel(form)
        self.label24.setGeometry(QtCore.QRect(285, 90, 31, 21))
        self.label24.setStyleSheet("border: 2px solid white")
        self.label24.setText("")
        self.label24.setObjectName("24")
        self.label25 = ClickableLabel(form)
        self.label25.setGeometry(QtCore.QRect(350, 90, 31, 21))
        self.label25.setStyleSheet("border: 2px solid white")
        self.label25.setText("")
        self.label25.setObjectName("25")
        self.label26 = ClickableLabel(form)
        self.label26.setGeometry(QtCore.QRect(400, 90, 31, 21))
        self.label26.setStyleSheet("border: 2px solid white")
        self.label26.setText("")
        self.label26.setObjectName("26")
        self.label27 = ClickableLabel(form)
        self.label27.setGeometry(QtCore.QRect(450, 90, 31, 21))
        self.label27.setStyleSheet("border: 2px solid white")
        self.label27.setText("")
        self.label27.setObjectName("27")
        self.label28 = ClickableLabel(form)
        self.label28.setGeometry(QtCore.QRect(20, 150, 31, 21))
        self.label28.setStyleSheet("border: 2px solid white")
        self.label28.setText("")
        self.label28.setObjectName("28")
        self.label29 = ClickableLabel(form)
        self.label29.setGeometry(QtCore.QRect(70, 150, 31, 21))
        self.label29.setStyleSheet("border: 2px solid white")
        self.label29.setText("")
        self.label29.setObjectName("29")
        self.label30 = ClickableLabel(form)
        self.label30.setGeometry(QtCore.QRect(120, 150, 31, 21))
        self.label30.setStyleSheet("border: 2px solid white")
        self.label30.setText("")
        self.label30.setObjectName("30")
        self.label31 = ClickableLabel(form)
        self.label31.setGeometry(QtCore.QRect(185, 150, 31, 21))
        self.label31.setStyleSheet("border: 2px solid white")
        self.label31.setText("")
        self.label31.setObjectName("31")
        self.label32 = ClickableLabel(form)
        self.label32.setGeometry(QtCore.QRect(235, 150, 31, 21))
        self.label32.setStyleSheet("border: 2px solid white")
        self.label32.setText("")
        self.label32.setObjectName("32")
        self.label33 = ClickableLabel(form)
        self.label33.setGeometry(QtCore.QRect(285, 150, 31, 21))
        self.label33.setStyleSheet("border: 2px solid white")
        self.label33.setText("")
        self.label33.setObjectName("33")
        self.label34 = ClickableLabel(form)
        self.label34.setGeometry(QtCore.QRect(350, 150, 31, 21))
        self.label34.setStyleSheet("border: 2px solid white")
        self.label34.setText("")
        self.label34.setObjectName("34")
        self.label35 = ClickableLabel(form)
        self.label35.setGeometry(QtCore.QRect(400, 150, 31, 21))
        self.label35.setStyleSheet("border: 2px solid white")
        self.label35.setText("")
        self.label35.setObjectName("35")
        self.label36 = ClickableLabel(form)
        self.label36.setGeometry(QtCore.QRect(450, 150, 31, 21))
        self.label36.setStyleSheet("border: 2px solid white")
        self.label36.setText("")
        self.label36.setObjectName("36")
        self.label41 = ClickableLabel(form)
        self.label41.setGeometry(QtCore.QRect(235, 180, 31, 21))
        self.label41.setStyleSheet("border: 2px solid white")
        self.label41.setText("")
        self.label41.setObjectName("41")
        self.label38 = ClickableLabel(form)
        self.label38.setGeometry(QtCore.QRect(70, 180, 31, 21))
        self.label38.setStyleSheet("border: 2px solid white")
        self.label38.setText("")
        self.label38.setObjectName("38")
        self.label39 = ClickableLabel(form)
        self.label39.setGeometry(QtCore.QRect(120, 180, 31, 21))
        self.label39.setStyleSheet("border: 2px solid white")
        self.label39.setText("")
        self.label39.setObjectName("39")
        self.label45 = ClickableLabel(form)
        self.label45.setGeometry(QtCore.QRect(450, 180, 31, 21))
        self.label45.setStyleSheet("border: 2px solid white")
        self.label45.setText("")
        self.label45.setObjectName("45")
        self.label40 = ClickableLabel(form)
        self.label40.setGeometry(QtCore.QRect(185, 180, 31, 21))
        self.label40.setStyleSheet("border: 2px solid white")
        self.label40.setText("")
        self.label40.setObjectName("40")
        self.label43 = ClickableLabel(form)
        self.label43.setGeometry(QtCore.QRect(350, 180, 31, 21))
        self.label43.setStyleSheet("border: 2px solid white")
        self.label43.setText("")
        self.label43.setObjectName("43")
        self.label37 = ClickableLabel(form)
        self.label37.setGeometry(QtCore.QRect(20, 180, 31, 21))
        self.label37.setStyleSheet("border: 2px solid white")
        self.label37.setText("")
        self.label37.setObjectName("37")
        self.label44 = ClickableLabel(form)
        self.label44.setGeometry(QtCore.QRect(400, 180, 31, 21))
        self.label44.setStyleSheet("border: 2px solid white")
        self.label44.setText("")
        self.label44.setObjectName("44")
        self.label42 = ClickableLabel(form)
        self.label42.setGeometry(QtCore.QRect(285, 180, 31, 21))
        self.label42.setStyleSheet("border: 2px solid white")
        self.label42.setText("")
        self.label42.setObjectName("42")
        self.label50 = ClickableLabel(form)
        self.label50.setGeometry(QtCore.QRect(235, 210, 31, 21))
        self.label50.setStyleSheet("border: 2px solid white")
        self.label50.setText("")
        self.label50.setObjectName("50")
        self.label47 = ClickableLabel(form)
        self.label47.setGeometry(QtCore.QRect(70, 210, 31, 21))
        self.label47.setStyleSheet("border: 2px solid white")
        self.label47.setText("")
        self.label47.setObjectName("47")
        self.label48 = ClickableLabel(form)
        self.label48.setGeometry(QtCore.QRect(120, 210, 31, 21))
        self.label48.setStyleSheet("border: 2px solid white")
        self.label48.setText("")
        self.label48.setObjectName("48")
        self.label54 = ClickableLabel(form)
        self.label54.setGeometry(QtCore.QRect(450, 210, 31, 21))
        self.label54.setStyleSheet("border: 2px solid white")
        self.label54.setText("")
        self.label54.setObjectName("54")
        self.label49 = ClickableLabel(form)
        self.label49.setGeometry(QtCore.QRect(185, 210, 31, 21))
        self.label49.setStyleSheet("border: 2px solid white")
        self.label49.setText("")
        self.label49.setObjectName("49")
        self.label52 = ClickableLabel(form)
        self.label52.setGeometry(QtCore.QRect(350, 210, 31, 21))
        self.label52.setStyleSheet("border: 2px solid white")
        self.label52.setText("")
        self.label52.setObjectName("52")
        self.label46 = ClickableLabel(form)
        self.label46.setGeometry(QtCore.QRect(20, 210, 31, 21))
        self.label46.setStyleSheet("border: 2px solid white")
        self.label46.setText("")
        self.label46.setObjectName("46")
        self.label53 = ClickableLabel(form)
        self.label53.setGeometry(QtCore.QRect(400, 210, 31, 21))
        self.label53.setStyleSheet("border: 2px solid white")
        self.label53.setText("")
        self.label53.setObjectName("53")
        self.label51 = ClickableLabel(form)
        self.label51.setGeometry(QtCore.QRect(285, 210, 31, 21))
        self.label51.setStyleSheet("border: 2px solid white")
        self.label51.setText("")
        self.label51.setObjectName("51")
        self.label71 = ClickableLabel(form)
        self.label71.setGeometry(QtCore.QRect(400, 300, 31, 21))
        self.label71.setStyleSheet("border: 2px solid white")
        self.label71.setText("")
        self.label71.setObjectName("71")
        self.label73 = ClickableLabel(form)
        self.label73.setGeometry(QtCore.QRect(20, 330, 31, 21))
        self.label73.setStyleSheet("border: 2px solid white")
        self.label73.setText("")
        self.label73.setObjectName("73")
        self.label58 = ClickableLabel(form)
        self.label58.setGeometry(QtCore.QRect(185, 270, 31, 21))
        self.label58.setStyleSheet("border: 2px solid white")
        self.label58.setText("")
        self.label58.setObjectName("58")
        self.label56 = ClickableLabel(form)
        self.label56.setGeometry(QtCore.QRect(70, 270, 31, 21))
        self.label56.setStyleSheet("border: 2px solid white")
        self.label56.setText("")
        self.label56.setObjectName("56")
        self.label55 = ClickableLabel(form)
        self.label55.setGeometry(QtCore.QRect(20, 270, 31, 21))
        self.label55.setStyleSheet("border: 2px solid white")
        self.label55.setText("")
        self.label55.setObjectName("55")
        self.label77 = ClickableLabel(form)
        self.label77.setGeometry(QtCore.QRect(235, 330, 31, 21))
        self.label77.setStyleSheet("border: 2px solid white")
        self.label77.setText("")
        self.label77.setObjectName("77")
        self.label79 = ClickableLabel(form)
        self.label79.setGeometry(QtCore.QRect(350, 330, 31, 21))
        self.label79.setStyleSheet("border: 2px solid white")
        self.label79.setText("")
        self.label79.setObjectName("79")
        self.label64 = ClickableLabel(form)
        self.label64.setGeometry(QtCore.QRect(20, 300, 31, 21))
        self.label64.setStyleSheet("border: 2px solid white")
        self.label64.setText("")
        self.label64.setObjectName("64")
        self.label60 = ClickableLabel(form)
        self.label60.setGeometry(QtCore.QRect(285, 270, 31, 21))
        self.label60.setStyleSheet("border: 2px solid white")
        self.label60.setText("")
        self.label60.setObjectName("60")
        self.label70 = ClickableLabel(form)
        self.label70.setGeometry(QtCore.QRect(350, 300, 31, 21))
        self.label70.setStyleSheet("border: 2px solid white")
        self.label70.setText("")
        self.label70.setObjectName("70")
        self.label81 = ClickableLabel(form)
        self.label81.setGeometry(QtCore.QRect(450, 330, 31, 21))
        self.label81.setStyleSheet("border: 2px solid white")
        self.label81.setText("")
        self.label81.setObjectName("81")
        self.label68 = ClickableLabel(form)
        self.label68.setGeometry(QtCore.QRect(235, 300, 31, 21))
        self.label68.setStyleSheet("border: 2px solid white")
        self.label68.setText("")
        self.label68.setObjectName("68")
        self.label67 = ClickableLabel(form)
        self.label67.setGeometry(QtCore.QRect(185, 300, 31, 21))
        self.label67.setStyleSheet("border: 2px solid white")
        self.label67.setText("")
        self.label67.setObjectName("67")
        self.label80 = ClickableLabel(form)
        self.label80.setGeometry(QtCore.QRect(400, 330, 31, 21))
        self.label80.setStyleSheet("border: 2px solid white")
        self.label80.setText("")
        self.label80.setObjectName("80")
        self.label75 = ClickableLabel(form)
        self.label75.setGeometry(QtCore.QRect(120, 330, 31, 21))
        self.label75.setStyleSheet("border: 2px solid white")
        self.label75.setText("")
        self.label75.setObjectName("75")
        self.label62 = ClickableLabel(form)
        self.label62.setGeometry(QtCore.QRect(400, 270, 31, 21))
        self.label62.setStyleSheet("border: 2px solid white")
        self.label62.setText("")
        self.label62.setObjectName("62")
        self.label57 = ClickableLabel(form)
        self.label57.setGeometry(QtCore.QRect(120, 270, 31, 21))
        self.label57.setStyleSheet("border: 2px solid white")
        self.label57.setText("")
        self.label57.setObjectName("57")
        self.label78 = ClickableLabel(form)
        self.label78.setGeometry(QtCore.QRect(285, 330, 31, 21))
        self.label78.setStyleSheet("border: 2px solid white")
        self.label78.setText("")
        self.label78.setObjectName("78")
        self.label59 = ClickableLabel(form)
        self.label59.setGeometry(QtCore.QRect(235, 270, 31, 21))
        self.label59.setStyleSheet("border: 2px solid white")
        self.label59.setText("")
        self.label59.setObjectName("59")
        self.label66 = ClickableLabel(form)
        self.label66.setGeometry(QtCore.QRect(120, 300, 31, 21))
        self.label66.setStyleSheet("border: 2px solid white")
        self.label66.setText("")
        self.label66.setObjectName("66")
        self.label69 = ClickableLabel(form)
        self.label69.setGeometry(QtCore.QRect(285, 300, 31, 21))
        self.label69.setStyleSheet("border: 2px solid white")
        self.label69.setText("")
        self.label69.setObjectName("69")
        self.label74 = ClickableLabel(form)
        self.label74.setGeometry(QtCore.QRect(70, 330, 31, 21))
        self.label74.setStyleSheet("border: 2px solid white")
        self.label74.setText("")
        self.label74.setObjectName("74")
        self.label76 = ClickableLabel(form)
        self.label76.setGeometry(QtCore.QRect(185, 330, 31, 21))
        self.label76.setStyleSheet("border: 2px solid white")
        self.label76.setText("")
        self.label76.setObjectName("76")
        self.label61 = ClickableLabel(form)
        self.label61.setGeometry(QtCore.QRect(350, 270, 31, 21))
        self.label61.setStyleSheet("border: 2px solid white")
        self.label61.setText("")
        self.label61.setObjectName("61")
        self.label63 = ClickableLabel(form)
        self.label63.setGeometry(QtCore.QRect(450, 270, 31, 21))
        self.label63.setStyleSheet("border: 2px solid white")
        self.label63.setText("")
        self.label63.setObjectName("63")
        self.label72 = ClickableLabel(form)
        self.label72.setGeometry(QtCore.QRect(450, 300, 31, 21))
        self.label72.setStyleSheet("border: 2px solid white")
        self.label72.setText("")
        self.label72.setObjectName("72")
        self.label65 = ClickableLabel(form)
        self.label65.setGeometry(QtCore.QRect(70, 300, 31, 21))
        self.label65.setStyleSheet("border: 2px solid white")
        self.label65.setText("")
        self.label65.setObjectName("65")
        self.strikes = QtWidgets.QLabel(form)
        self.strikes.setGeometry(QtCore.QRect(20, 380, 451, 16))
        self.strikes.setStyleSheet("color: red")
        self.strikes.setText("")
        self.strikes.setObjectName("strikes")

        self.retranslate_ui(form)
        # noinspection PyArgumentList
        QtCore.QMetaObject.connectSlotsByName(form)

    # noinspection PyMethodMayBeStatic
    def retranslate_ui(self, form):
        _translate = QtCore.QCoreApplication.translate
        # noinspection PyArgumentList
        form.setWindowTitle(_translate("Form", "Sudoku"))

    def keypress(self, event):
        """
        Keypress event handler
        :param event: keypress event
        """
        if data.gridobj.selected is not None:
            x, y = data.gridobj.selected
            cube = data.gridobj.cubes[x][y]
            key = event.key()
            if key == QtCore.Qt.Key_Backspace:
                if cube.value == 0 and cube.temp != 0:
                    cube.temp = 0
                    data.labels[x][y].setText("")
                print('Backspace')
            elif key == QtCore.Qt.Key_Space:
                print("Space")
                solve(data.gridobj.board)
                print_board(data.gridobj.board)
                for rowcounter in range(0, 9):
                    for colcounter in range(0, 9):
                        if data.gridobj.board[rowcounter][colcounter] != 0:
                            data.gridobj.cubes[rowcounter][colcounter].value = data.gridobj.board[rowcounter][colcounter]
                            data.labels[rowcounter][colcounter].setText(str(data.gridobj.board[rowcounter][colcounter]))
                            data.labels[rowcounter][colcounter].setStyleSheet("color: rgb(40, 255, 6); border: "
                                                                         "2px solid white !important")
            elif key == QtCore.Qt.Key_Return:
                if cube.temp != 0 and cube.value == 0:
                    cube.value = cube.temp
                    data.gridobj.model = [
                            [data.gridobj.cubes[col][row].value for row in range(data.gridobj.rows)
                        ] for col in range(data.gridobj.cols)
                    ]
                    if valid(data.gridobj.board, x, y, cube.value) and solve(data.gridobj.model):
                        data.gridobj.board[x][y] = cube.value
                        data.labels[x][y].setText(str(cube.value))
                        data.labels[x][y].setStyleSheet("color: rgb(40, 255, 6); border: "
                                                                 "2px solid white !important")
                    else:
                        cube.temp = 0
                        cube.value = 0
                        data.gridobj.model = [
                            [data.gridobj.cubes[col][row] for row in range(data.gridobj.rows)
                             ] for col in range(data.gridobj.cols)
                        ]
                        data.labels[x][y].setText("")
                        strikes_text = self.strikes.text()
                        self.strikes.setText(strikes_text+" X")


                print("Enter")
            else:
                if event.text().isdigit() and cube.value == 0 and int(event.text()) != 0:
                    cube.temp = int(event.text())
                    data.labels[x][y].setText(event.text())
                    data.labels[x][y].setStyleSheet("border: 2px solid red; color: rgb(243, 219, 9)")
                print(event.text())